### ISSUE TITLE
Using XYFrame only if table can not fit in the screen?

### ISSUE THREAD

**Issue by suravi-r** [Akascape/CTkXYFrame#1]
Hi, I have multiple tables on my UI and the size of the table is all different. Does anyone know how to use the scrollable frame ONLY when the table can't "fit" in the original frame? I'm using the Table widget you created btw!

**Comment by Akascape** [comment]
@suravi-r this widget automatically hides the scrollbars when the table fit the screen.

**Comment by suravi-r** [comment]
Oh okay, perfect! Is there anyway I could enable only one of the scrolling? Like I just need it to scroll horizontally (Y) if the number of columns is large

**Comment by Akascape** [comment]
@suravi-r In that case use the customtkinter scrollframe. Ctkxyframe hides the scrollbars dynamically.

**Comment by suravi-r** [comment]
oh okay, thank you so much!
