### ISSUE TITLE
Bug Found: CTkXYFrame moving with CTkScrollableFrame

### ISSUE THREAD

**Issue by Gh05tJr** [Akascape/CTkXYFrame#11]
Hi @Akascape I am Using CTkXYFrame inside CTkScrollableFrame and when I am scrolling the CTkXYFrame it is working normally but when I am scrolling the CTkScrollableFrame the CTkXYFrame is automatically scrolling with it.

Video 👇👇👇👇

https://github.com/Akascape/CTkXYFrame/assets/110291267/2a258aa2-1eb7-4b1c-bfad-67664d590a47

Hoping that you fix this soon.......

**Comment by Akascape** [comment]
@DIY-TECH-HACKER Fixed, test the new version.

**Comment by Gh05tJr** [comment]
Thank you. It is working perfectly
