### ISSUE TITLE
Bug: Light mode not activated properly.

### ISSUE THREAD

**Issue by ghost** [Akascape/CTkXYFrame#2]
### Screenshot:

![Screen Shot 2023-07-21 at 1 53 30 PM](https://github.com/Akascape/CTkXYFrame/assets/130259005/95ffceb4-7359-4d61-8835-f082d84ccfa0)

### Issue:
As seen in the screenshot, the `CTkXYFrame` does not change to light mode properly. If we determine this is an issue with CustomTkinter, I will transfer the issue.

The code for the usage of this extension can be found [here](https://github.com/dishb/hive/blob/main/core/file_explorer.py).

### Example:
```python
import customtkinter as ctk

from CTkXYFrame import CTkXYFrame

def dark_mode(*args):
    ctk.set_appearance_mode("dark")

def light_mode(*args):
    ctk.set_appearance_mode("light")

app = ctk.CTk()
app.geometry("700x600")

frame = CTkXYFrame(master = app)
frame.grid(row = 0, column = 0, sticky = "nsew")

label = ctk.CTkLabe(master = frame, text = "label")
label.grid(row = 0, column = 0, sticky = "nsew")

button = ctk.CTkButton(master = frame, text = "button")
button.grid(row = 1, column = 0, sticky = "nsew")

app.bind("d", dark_mode)
app.bind("l", light_mode)

app.mainloop()

```

### Specs:
macOS `12.6.7`
Python `3.11.4`
CustomTkinter `5.2.0`
CTkXYFrame `unsure`

**Comment by ghost** [comment]
After copying the new `ctk_xyframe.py` file, looks like one line was changed... I'll try with the new file now.

EDIT: After using the most up to date version of `CTkXYFrame`, the issue still persists.

**Comment by Akascape** [comment]
@dishb Fixed, try the new version!

**Comment by ghost** [comment]
Great, thanks!
