### ISSUE TITLE
CTkTable not spanning the entire row

### ISSUE THREAD

**Issue by matinwgg** [Akascape/CTkXYFrame#4]
table = CTkXYFrame(master=app)
      table.pack(expand=True, fill="both", padx=10, pady=(100, 0))

    ctk_table = CTkTable(table, row=20, column=1,
                         values=value, font=LABEL_FONT, anchor='w')

I have one column here which i expected it to span the entire row

**Comment by Akascape** [comment]
@matinwgg In that case use CTkScrollableFrame, if you span one row then the horizontal scrollbar has no use, if you span columns then vertical scrollbar has no use. XYFrame is different and have both the axis at the same time.
