### ISSUE TITLE
cant find module

### ISSUE THREAD

**Issue by GalaxyPhoenix716** [Akascape/CTkXYFrame#5]
i have kept the main file in proper destination but it is still showing module not found

**Comment by jidukrishna** [comment]
![image](https://github.com/Akascape/CTkXYFrame/assets/74850929/0af4759a-35e9-4809-9fd1-99764d852771)

did u take that folder inside the downloaded folder ? also u should keep the folder in ur working dir. it should look something like this

**Comment by GalaxyPhoenix716** [comment]
> ![image](https://user-images.githubusercontent.com/74850929/272539063-0af4759a-35e9-4809-9fd1-99764d852771.png)
> 
> did u take that folder inside the downloaded folder ? also u should keep the folder in ur working dir. it should look something like this

yes i did the same

**Comment by Akascape** [comment]
@GalaxyPhoenix716 Properly check the spellings and also test the examples given there.
