### ISSUE TITLE
How to set Height Width of CTkXYFrame

### ISSUE THREAD

**Issue by sunny9495-dev** [Akascape/CTkXYFrame#6]
Hi @Akascape 

I tried the `place` instead of `pack` but its not working

Here is the code I tried.

`frm_cscan_widgets = CTkXYFrame(master=root, width=200, height=150)`
`frm_cscan_widgets.place(x=10, y=140)`

I see the width, height isn't working. Here is the screenshot

[https://i.imgur.com/CJ5s6no.png](https://i.imgur.com/CJ5s6no.png)

Any help would be appreciated.

**Comment by Akascape** [comment]
@sunny9495-dev Fixed now. update to the latest version.
