### ISSUE TITLE
QUESTION: What are the handles to grab the width and height of the scrollbars?

### ISSUE THREAD

**Issue by matthew-efseaff** [Akascape/CTkXYFrame#8]
I've looked through the CTkScrollableFrame and the CTkScrollbar, but I can't figure out how to interact with CTkXYFrame scrollbars... I'd like to make them 'fatter' so that they are easier to see.
I see how to change their color, but that won't be enough to make them more accessible.
Thank you

**Comment by Akascape** [comment]
@matthew-efseaff Update to the new version, I have added `scrollbar_width` parameter.
