### ISSUE TITLE
maximum recursion depth exceeded

### ISSUE THREAD

**Issue by ViktorWeissenborn** [Akascape/CTkXYFrame#9]
Hello (:

If you take your example_1.py and try to execute the code with CTkOptionMenu instead of CTkButton you get an infinite recursion error in the terminal that doesn't end. 

There is also no further information given by the traceback than "Exception in Tkinter callback"

I tried to fix this without any luck, maybe someone else will be able to.

Here is the code if someone wants to try it out:

`
import customtkinter
from CTkXYFrame import *

root = customtkinter.CTk()

xy_frame = CTkXYFrame(root)
xy_frame.pack(fill="both", expand=True, padx=10, pady=10)

for i in range(20):
    for j in range(10):
        customtkinter.CTkOptionMenu(xy_frame).grid(row=i, column=j, padx=5, pady=5)
    
root.mainloop()
`

Good Luck!
Viktor

**Comment by Akascape** [comment]
@ViktorWeissenborn Not happening in my system:
![image](https://github.com/Akascape/CTkXYFrame/assets/89206401/6926f69b-8a7a-4401-8337-21e42b352332)

Change your recursion limit for loop:
https://stackoverflow.com/questions/3323001/what-is-the-maximum-recursion-depth-and-how-to-increase-it

**Comment by ViktorWeissenborn** [comment]
Hey thanks for the reply,

its still not working though I set the recursion limit to 10 million. I took the other way and used a canvas to add two scrollbars.
